### ISSUE TITLE
Workout listing mixes volume and density cycle

### ISSUE THREAD

**Issue by asilenzi** [emh/volumecycles#1]
Hi @emh ,

I loaded the page with the default settings and I found that at the end of a volume cycle, the load progresses in the following way (screenshot attached):

of 16kg:
18x6 -> 20x6 -> 12x10 -> 18x7

for 24kg
18x4 -> 20x4 -> 8x10 -> 18x5

for 32kg
18x3 -> 20x3 -> 6x10 -> 18x4

I suspect the 10 reps training are an artefact.

<img width="713" alt="Screenshot 2021-05-03 at 12 25 20" src="https://user-images.githubusercontent.com/2511784/116865882-c504ab00-ac0a-11eb-9f82-4d5324b1a771.png">

I know nothing about svelte, but I can try a PR if you want.

Cheers

Alessandro

**Comment by asilenzi** [comment]
I did a bit more digging. I think I created this issue because our interpretation of the 2 cycles differ.

This is my first time looking touching Svelte.
https://github.com/emh/volumecycles/pull/2

I think this will introduce a change unwanted by @emh:
All volume cycles will be completed before the density cycle workouts are listed

edit: grammar

**Comment by asilenzi** [comment]
I attach here a screenshot, I think it does match the density cycle explained [here at minute ~2](https://www.youtube.com/watch?v=HuNB0kfiUXk).

<img width="409" alt="Screenshot 2021-05-03 at 16 55 57" src="https://user-images.githubusercontent.com/2511784/116892807-841f8d00-ac30-11eb-8420-2dea9a274ecb.png">

**Comment by emh** [comment]
now i understand what you were talking about -- the thing is, that was intentional, the mixing of the two cycles. i wanted the workouts to be sorted just by volume.

i was considering adding a checkbox to the form however to turn that off, because you are correct - in wildman's original explanation, the density cycle starts after the volume cycle (though he never touches on how a density cycle would fit into a rolling volume cycle but maybe that will come up in a future video)

i'll have a look at your changes today - i really do appreciate you reporting this and working on it! thank you.

**Comment by asilenzi** [comment]
If it goes against the design, I can scrap some changes.

I believe that there are few changes in this PR that could be split in few parts:
- the way the reps are calculated in the density cycle.
- the way workouts are ordered

I believe my main issue was that the workouts per weight are put "out-of-order" by sorting per volume.
One could keep a `order` counter per weight and consider that in the sorting or something like that.

Happy to help!

**Comment by emh** [comment]
@asilenzi can you try the latest code and let me know if it solves your issues? i believe it should!

**Comment by asilenzi** [comment]
It solves the issue!

Good job
